# This is a basic workflow to help you get started with Actions

name: CI - Allow new features from account service

# Controls when the workflow will run
on:
  push:
    branches:
      - dev
    paths:
      - 'account-service/**'
  pull_request:
    branches:
      - dev 
    paths:
      - 'account-service/**'
    
jobs:
  account-test:
    runs-on: ubuntu-latest
    environment: dev-secrets

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 10
          ref: dev

      - name: Try to test new integration
        run: |
          cd account-service/
          mvn compile 
          mvn test