name: Test the secrets from vault

on:
  push:
    branches: [ master ]

jobs:
    build:
      runs-on: ubuntu-latest
      environment: test-vault
      steps:
        - name: Import Secrets
          uses: hashicorp/vault-action@v1.5.0
          with:
            url: https://52.143.251.183:8200
            token: ${{ secrets.VaultToken }}
            #caCertificate: ${{ secrets.VAULTCA }}
            secrets: |
                kv/test test | TEST ;
      
        - run: |
            echo '${{ steps.secrets.outputs.TEST }}'