name: Test vault secrets

on:
  push:
    branches: [ master ]

jobs:
    build:
      runs-on: ubuntu-latest
      environment: test-vault
      steps:
        - name: Import Secrets
          uses: hashicorp/vault-action@v2.3.1
          with:
            url: http://52.143.251.183:8200
            token: ${{ secrets.VaultToken }}
            caCertificate: ${{ secrets.VAULTCA }}
            secrets: |
                kv/user user | USER ;
                kv/passwd passwd | PASSWD ;
      
        - run: |
            az login -u ${{ steps.secrets.outputs.USER }} -p ${{ steps.secrets.outputs.PASSWD }} 
