# This is a basic workflow to help you get started with Actions

name: CI - Allow new features from config

# Controls when the workflow will run
on:
  push:
    branches:
      - dev
  pull_request:
    paths:
      - 'config/'
    
jobs:
  config-test:
    runs-on: ubuntu-latest
    environment: dev-secrets

    steps:
      - uses: actions/checkout@v2

      - name: Test new integration
        run: |
          cd config/
          mvn compile
          mvn test

